### ISSUE TITLE
Kasm link is blocked 

### ISSUE THREAD

**Issue by Adithr123** [GikitSRC/DuckOS#12]
My school's IT is competent, so any IP address links are blocked. An actual link/replit deployment link would be helpful. The source code would also be greatly appreciated—many thanks for considering my request.

**Comment by GikitSRC** [comment]
There's no source code for the Kasm server, Kasm is their own company and we're merely hosting it. For the blocked links problem, we have 16 alternative links on our Discord Server but here's one of them:
https://i-think-i.lol/

**Comment by PHYT90DitYT** [comment]
Looks like 1mp alr got to this ticket lol
