### ISSUE TITLE
Alternate Urls?

### ISSUE THREAD

**Issue by urmom345** [GikitSRC/DuckOS#5]
I love this idea of a portable operating system like another one I watch (Clockwork) but this one is blocked unlike the other one. It looks like it has many more features and I would love to try it but...... Its blocked in my school and would love to try it on another link

**Comment by GikitSRC** [comment]
Apologies for the inconvenience! In case you're unable to access Skyhax, you have the option to host it independently. We understand that this may not be the most convenient solution, but we are actively working towards acquiring alternate domains in the near future. Presently, we lack the necessary funds to secure one.

Could you please provide further details regarding the nature of the block? Is the entire domain inaccessible, or are specific extensions blocking it?

Once again, we sincerely apologize for any difficulties you may be experiencing. At the moment, your alternatives are to host DuckOS on your own or patiently await our acquisition of additional domains.

**Comment by urmom345** [comment]
Its a extension and ive tried disabling it with different methods but none work

**Comment by urmom345** [comment]
I also can't find out how to independently host
