### ISSUE TITLE
You want some help, like a partner?

### ISSUE THREAD

**Issue by pickle69420** [GikitSRC/DuckOS#6]
You don't have to accept...but I kind of am bored. The proxy I was working on got threatened by my principal so now I pretty much have nothing to do.

**Comment by GikitSRC** [comment]
Nah, I'm fine with only 1 other person helping me, but thanks!

**Comment by pickle69420** [comment]
Yeah but incase u wanna use [this](https://github.com/pickle69420/picklebox) i give you permission.

**Comment by GikitSRC** [comment]
whoa that looks amazing

Question tho, what proxy does it use? Or did you make it yourself?

**Comment by pickle69420** [comment]
It just uses UltraViolet, cuz im not THAT smart.

**Comment by TheGlitchedPhoenix** [comment]
bro, some schools don't even know how to block uv they just scan the URLS and the name
